#配置数据库连接参数
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.175.131:3307/limit_time_buy?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
#配置关联resource下的mapper包下的mapper.xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml